# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

addons:
  postgresql: "9.6"

jobs:
  include:
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.0
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.1
      dist: focal
      addons:
        postgresql: "12"
    - name: "PHP: 8.2"
      dist: jammy
      language: ruby # This makes no sence to me, but it works!
      addons:
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.2 php8.2-mbstring
        - php -v
        - sudo apt-get install postgresql-16 postgresql-client-16
        - "sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/16/main/postgresql.conf 2>&1"
        - sudo /etc/init.d/postgresql restart
    - name: "PHP: 8.3"
      dist: jammy
      language: ruby # This makes no sence to me, but it works!
      addons:
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.3 php8.3-mbstring
        - php -v
        - sudo apt-get install postgresql-16 postgresql-client-16
        - "sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/16/main/postgresql.conf 2>&1"
        - sudo /etc/init.d/postgresql restart

before_script:
  - composer update --dev
  - sudo -u postgres psql -c "CREATE DATABASE test;" -U postgres 2>&1
  - sudo -u postgres psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres 2>&1
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres 2>&1
  - sudo -u postgres psql -c "GRANT ALL ON SCHEMA public TO test" -U postgres test 2>&1

script:
  - cd test && ../vendor/bin/run_unit_tests
